### ISSUE TITLE
Videos start slower in prod, so first question pauses too early

### ISSUE THREAD

**Issue by evjan** [evjan/stripetime#2]
It should probably look at what the currentTime of the video is and stop once it reaches e.g. question_video_end or answer_video_end.

**Comment by juanojeda** [comment]
Two ways this could be handled:

**Comment by juanojeda** [comment]
Merged in `bugfix/issue-02-video-playback-timing` to fix this, and added some comments around potential other issues, and potential fixes.

**Comment by evjan** [comment]
@juanojeda Re-opening this, as it unfortunately doesn't seem to work well at all on mobiles. In Chrome and Firefox on my Nexus you don't see any video at all until after answering the first question. Maybe we need to actually look at what second the video is currently at every now and then?
